MarketGo/urls.py
from django.contrib import admin
from django.urls import path , include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('product.urls')),
    path('core/',include('core.urls')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('checkout/',include('checkout.urls')),
    path('paypal/',include('paypal.standard.ipn.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import CartAddView, CartDetailView, CartRemoveView,CartUpdateQuantityView

app_name = 'cart'

urlpatterns = [
    path('', CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', CartAddView.as_view(), name='cart_add'),
     path('update_quantity/<int:product_id>/', CartUpdateQuantityView.as_view(), name='update_quantity'),
    path('remove/<int:product_id>/', CartRemoveView.as_view(), name='cart_remove'),

]

checkout/urls.py
from django.urls import path
from .views import CheckoutView,InvoiceDetailView


app_name ="checkout"
urlpatterns = [
    path('', CheckoutView.as_view(), name='checkout'),
    path('invoice/<int:pk>/', InvoiceDetailView.as_view(), name='invoice'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),


]

core/urls.py
from django.urls import path
from .views import LoginView, LogoutView, RegisterView , MyAccountView

app_name = 'core'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('myaccount/',MyAccountView.as_view() , name='myaccount'),


    # other URL patterns for your app
]

product/urls.py
from django.urls import path , include
from .views import HomeView,ScanView,SearchProductView


app_name ='product'
urlpatterns = [
    path('', HomeView.as_view(), name='home_view'),
    path('scan', ScanView.as_view(), name='scan_view'),
    path('search', SearchProductView.as_view(), name='search_product'),

    ]

checkout/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from product.models import Product

class Order(models.Model):


    user = models.ForeignKey(User, related_name='orders', blank=True, null=True, on_delete=models.CASCADE)
    
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    
    created_at = models.DateTimeField(auto_now_add=True)

    paid = models.BooleanField(default=False)
    paid_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)


    def __str__(self):
        return f"Order #{self.id} - {self.first_name} {self.last_name} {self.paid_amount} {self.created_at}"

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.CASCADE)
    price = models.FloatField()
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.name} in Order #{self.order.id}"

checkout/forms.py
from django import forms
from .models import Order

class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'phone', 'paid_amount']

checkout/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import DetailView
from django.views.generic import FormView
from product.models import Product
from .models import Order, OrderItem
from .forms import CheckoutForm
from cart.cart import Cart
from django.urls import reverse


class CheckoutView(LoginRequiredMixin, FormView):
    template_name = 'checkout.html'
    form_class = CheckoutForm

    def form_valid(self, form, *args, **kwargs):
        cart = Cart(self.request)
        if not cart.cart:  # If the cart is empty, redirect to the cart page
            return redirect('cart:cart_detail')
    #   Calculate total price 

  
        order = form.save(commit=False)
        order.user = self.request.user

        # Save total amount in DB 


        order.save()

        # Create OrderItems for each item in the cart
        for item in cart:
            product = item['product']
            order_item=OrderItem.objects.create(
                order=order,
                product=product,
                price=item['price'],
                quantity=item['quantity'],
            )
        print(order_item)
        

        print(order)
        print(order.paid_amount)



        
        # Optionally, you can clear the cart after placing the order
        cart.clear()


        # return HttpResponse('Order placed successfully!')
        return redirect(reverse('checkout:invoice', kwargs={'pk': order.id}))




    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form, *args, **kwargs)
        else:
            print(form.errors)
            return self.form_invalid(form, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['cart'] = Cart(self.request)
        return context
    





class InvoiceDetailView(DetailView):
    template_name = 'invoice.html'
    context_object_name = 'order'  # This sets the variable name in the template
    model = Order  # This sets the model for the view

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = context['order']

        # Add related OrderItem instances to the context
        context['order_items'] = OrderItem.objects.filter(order=order)
        print(context)
        return context

MarketGo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>MarketGo</title>
        <!-- Favicon-->
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->

        {% include 'navbar.html'%}
        {% if messages %}
            {% for message in messages %}

            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        {% endif %}


        {% block content%}
        {% endblock%}

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; MarketGo 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

MarketGo/templates/cart_detail.html
{% extends 'base.html'%}
{% load static %}
{% block content%}



{% if cart %}


{% for item in cart %}
</br></br>
<div class="col-8 card mb-3" style="max-width: 540px; left: 75px;">
</br>
    <div class="row g-0" >
        <div class="col-md-4">
            {% if item.product.image %}
            <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" class="img-fluid" height="200" width="200" >
            {% endif %}
        </div>
        <div class="col-md-8">
        <div class="card-body">
        <h5 class="card-title">{{ item.product.name }}</h5>
        </br>


        <div class="container">
            <div class="row">
                
               
            <!-- Force next columns to break to new line -->
            <div class="w-100"></div>
          
              
              <div class="col-6 col-m-3">Unit_Price</div>
              <div class="col-6 col-m-3">{{ item.price}} dh</div>
              <div class="w-100"></div>
              <div class="col-6 col-m-3">Total_Price</div>
              <div class="col-6 col-m-3">{{ item.total_price}} dh</div>
            </div>
        

    </br>


          
<!-- Update Quantity Button -->
<div class="row">
    {% if item.category == 'unit' %}
        <div class="col-12 col-md-6 mb-2">
            <form action="{% url 'cart:update_quantity' item.product.id %}" method="post" class="d-flex">
                {% csrf_token %}
                <button type="submit" name="action" value="decrease" class="btn btn-secondary">-</button>
                <span class="mx-2">{{ item.quantity }}</span>
                <button type="submit" name="action" value="increase" class="btn btn-secondary">+</button>
            </form>
        </div>
    {% endif %}
    
    <div class="col-12 col-md-6 d-grid gap-2 d-md-flex justify-content-md-end">
        <form action="{% url 'cart:cart_remove' item.product.id %}" method="POST">
            <input class="btn btn-primary me-md-2" type="submit" value="Remove">
            {% csrf_token %}
        </form>
    </div>
</div>


        


    </div>

            </div>
        </div>
    </div>
</div>



{% endfor %}

<div class="card my-4">
    <div class="card-body">
        <h5 class="card-title">Total</h5>
        <h3 class="card-text">{{ cart.get_total_price }} dh</h3>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-3">
            <a type="button" class="btn btn-primary btn-sm me-2" href="{% url 'product:home_view' %}">Continue Shopping</a>
            <a type="button" class="btn btn-secondary btn-sm" href="{% url 'checkout:checkout' %}">Checkout</a>
        </div>
    </div>
</div>


<!-- 
<div class="card" style="margin: 20px;"  >
    <div class="card-body" sty>
      <h5 class="card-title">Total</h5>
      <h3 class="card-text">{{cart.get_total_price}} dh</h3>
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a type="button" class="btn btn-primary btn-sm" href="{% url 'product:home_view' %}">Continue Shopping</a>
        <a type="button" class="btn btn-secondary btn-sm" href="{% url 'checkout:checkout' %} "> Checkout </a>
    </div>
    
    </div>
  </div> -->


{% else %}
</br></br> 
</br></br> 

</br></br> 

</br></br> 

<center> <h1>Cart Is Empty !</h1>
    
</center>
</br></br> 
</br></br> 
</br></br> 

<p class="d-grid gap-2 d-md-flex justify-content-md-end">
    <a type="button" class="btn btn-primary btn-sm" href="{% url 'product:home_view' %} " style="margin-right: 50px;">Continue Shopping</a>

</p>

 
</br></br> 
{% endif%}
{% endblock %}

MarketGo/templates/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <form action="{% url 'checkout:checkout' %}" method="POST" class="row g-3">
        {% csrf_token %}

        <div class="col-md-4 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Your cart</span>
                <span class="badge badge-secondary badge-pill">3</span>
            </h4>

            <div class="table-responsive order_table checkout">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Price</th>
                            <th scope="col">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart %}
                        <tr>
                            <td>
                                <img src="{{ MEDIA_URL }}{{ item.product.image.url }}" alt="{{ item.product.name }}"
                                    class="img-fluid mb-3" height="100px" width="100px">
                                <h6 class="w-160 mb-5">{{ item.product.name }}</h6>
                            </td>
                            <td>
                                <h6 class="text-muted">{{ item.quantity }}</h6>
                            </td>
                            <td>
                                <h5 class="text-muted">{{ item.price }} dh</h5>
                            </td>
                            <td>
                                <h5 class="text-brand">{{ item.total_price }} dh</h5>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="d-flex align-items-end justify-content-between mb-3">
                <h6 class="text-muted">Total:</h6>
                <h6 class="text-brand">{{ cart.get_total_price }} dh</h6>
            </div>
        </div>

        <div class="col-md-8 order-md-1">
            <h4 class="mb-3">Billing address</h4>

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="id_first_name" class="form-label">First Name</label>
                    <input id="id_first_name" name="first_name" value="{{ user.first_name }}" class="form-control"
                        required>
                </div>

                <div class="col-md-6 mb-3">
                    <label for="id_last_name" class="form-label">Last Name</label>
                    <input id="id_last_name" name="last_name" value="{{ user.last_name }}" class="form-control"
                        required>
                </div>
            </div>

            <div class="mb-3">
                <label for="id_email" class="form-label">Email</label>
                <input id="id_email" name="email" value="{{ user.email }}" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="id_phone" class="form-label">Phone</label>
                <input type="text" id="id_phone" name="phone" class="form-control"  value="{{ form.phone.value | default:'' }}" required>
            </div>
            
            <input type="hidden" name="paid_amount" value="{{ cart.get_total_price }}">

            <!-- Payment -->
            <div class="mb-4">
                <h4 class="mb-3">Payment</h4>
                <div class="col-12 mt-4">
                    <button class="btn btn-primary">Confirm Checkout</button>
                </div>
            </div>
        </div>
    </form>
</div>
</br></br>
{% endblock %}

MarketGo/templates/home.html
{% extends 'base.html'%}
{% block content%}
{% csrf_token %}
<Section>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
   
        </br>  </br>
                <h1 class="text-center mb-4">Search for a Product</h1>

                <!-- Add a button for scanning the barcode -->
                <button type="button" id="scanButton" class="btn btn-primary">Scan Product</button>

                <form action="{% url 'product:home_view' %}" method="GET" class="mt-4">

                    <div class="form-group">

                        <label for="barcode">Enter Barcode:</label>

                        <input type="text" id="barcode" name="barcode" required class="form-control">

                    </div>

                    <button type="submit" class="btn btn-primary mt-2">Search</button>

                </form>
                
                <br/>
                {% if product %}
                    <div class="card mt-5">
                        <div class="card-header">
                            <h2>{{ product.name }}</h2>
                        </div>
                        <div class="card-body">
                            <!-- Display the product image -->
                            {% if product.image %}
                                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="img-fluid mb-3">
                            {% endif %}
                            <p><strong>Description:</strong> {{ product.description }}</p>
                            <p><strong>Price:</strong> ${{ product.price }}</p>
                            <p><strong>Category:</strong> {{ product.category }}</p>
                            <p><strong>EAN Barcode:</strong> {{ product.barcode }}</p>

                            {% if product.category == 'unit' %}
                                <p><strong>Stock Quantity:</strong> {{ product.stock_quantity }}</p>
                                <form method="post" action="{% url 'cart:cart_add' product.id %}">
                                    {% csrf_token %}
                                    <label for="quantity">Quantity:</label>
                                    <input type="number" name="quantity" value="1" min="1" >
                                    <button type="submit" class="btn btn-outline-dark">
                                        <i class="bi-cart-fill me-1"></i>
                                        Add To Cart
                                    </button>
                                </form>
                            {% elif product.category == 'weight' %}
                                <p><strong>Weight:</strong> {{ product.weight }} kg</p>
                                <form method="post" action="{% url 'cart:cart_add' product.id %}">
                                    {{ cart_product_form }}
                                    {% csrf_token %}
                                    <label for="quantity">Weight (kg):</label>
                                    <input type="number" name="quantity" value="1" min="1" max="1">
                                    <button type="submit" class="btn btn-outline-dark">
                                        <i class="bi-cart-fill me-1"></i>
                                        Add To Cart
                                    </button>
                                </form>
                            {% endif %}

                        </div>
                        
                    </div>
                {% elif product_not_found %}
                    <p class="text-center mt-5"><strong>Product not available.</strong></p>
                {% endif %}
                <br/><br/>
                <br/><br/>
                <br/><br/>
                <br/><br/>
                <br/>
             
            </div>
        </div>
    </div>

</Section>
    
    <!-- Include jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <script>
        // Redirect to scan_logic.html when the "Scan Product" button is clicked
        document.getElementById("scanButton").addEventListener("click", function () {
            window.location.href = "{% url 'product:scan_view' %}";
        });
    </script>

    <!-- Include Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybB5IXNxFwWQfE7u8Lj+XJHAxKlXiG/8rsrtpb6PEdzD828Ii" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>



    {% endblock%}

MarketGo/templates/invoice.html
{% extends 'base.html'%}
{% load static %}
{% block content%}


<!-- Invoice 1 - Bootstrap Brain Component -->
<section class="py-3 py-md-5">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-lg-9 col-xl-8 col-xxl-7">
          <div class="row gy-3 mb-3">
              <div class="col-6">
                <h2 class="text-uppercase text-endx m-0">Invoice</h2>
              </div>

          </div>




        <div class="row mb-3">

            <div class="col-12 col-sm-6 col-md-8">
              <h4></h4>
              <address>
                <strong>{{order.first_name}} {{order.last_name}}</strong>
                <br>Phone: {{order.phone}}0<br>
                Email: {{order.email}}
              </address>
            </div>








            <div class="col-12 col-sm-6 col-md-4">

                <h4 class="row">
                  <span class="col-6">Invoice #</span>
                </h4>

                <div class="row">
              
                  <span class="col-6">Order ID</span>
                  <span class="col-6 text-sm-end">#{{ order.id }}</span>
                  <span class="col-6">Invoice Date</span>
                  <span class="col-6 text-sm-end">{{ order.created_at }}</span>
                </div>


            </div>
        </div>


          <div class="row mb-3">
            <div class="col-12">
              <div class="table-responsive">
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th scope="col" class="text-uppercase">Qty</th>
                      <th scope="col" class="text-uppercase">Product</th>
                      <th scope="col" class="text-uppercase text-end">Unit Price</th>
                      <th scope="col" class="text-uppercase text-end">Amount</th>
                    </tr>
                  </thead>
                  <tbody class="table-group-divider">
                    {% for order_item in order_items %}

                    <tr>
                      <th scope="row">{{ order_item.quantity }}</th>
                      <td>{{ order_item.product.name }}</td>
                      <td class="text-end">{{ order_item.product.price }} </td>
                      <td class="text-end"> {{ order_item.price }} </td>
                    </tr>
                    {% endfor %}

                 
                   
                   

                    <tr>
                      <th scope="row" colspan="3" class="text-uppercase text-end">Total</th>
                      <td class="text-end">{{ order.paid_amount }} dh</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>









        </div>
      </div>
    </div>
  </section>
{% endblock %}

MarketGo/templates/login.html
{% extends 'base.html'%}
{% block content%}
{% csrf_token %}

        <!-- Header-->
    
       <div class="container">
        <div class="row">
            <div class="col-6">
            </br>  </br>
        </br>  </br>
            <center>
                <div class="col-8">
                    <br/> <br/> 
                    <form method="POST" action="{% url 'core:login' %}">
                        {% csrf_token %}
                        <div class="mb-3">
                          <input type="text" class="form-control" name="username" placeholder="Enter Your Username">
                            </div>
                        <div class="mb-3">
                          <input type="password" class="form-control" name="password" placeholder="Enter Your Password">
                        </div>
                        <button type="submit" class="btn btn-secondary">Login</button>
                      </form>

<br/><br/>

                </div>
            </center>
            </div>
            <div class="col-6">
            </br>  </br>
                <img src="/media/homepage_img.png">
            </br>  </br>
        </br>  </br>
    </br>  </br>
           
            </div>

 
        </div>
       </div>
 {% endblock%}

MarketGo/templates/navbar.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="color: #80dab4;">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'product:home_view' %}"><img src="\media\logo.png" alt=""></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                {% if user.is_authenticated %}
                    {% if request.path == '/core/login/' %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'product:home_view' %}">Home</a></li>
                    {% else %}
            

                <li class="nav-item"><a href="{% url 'product:home_view' %}" class="nav-link active" aria-current="page" >Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">My account</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:logout' %}">Logout</a></li>
               
                {% endif %}
            </ul>


            <div class="input-group-prepend" style="background-color: #e3f2fd; margin-right: 10px;">
                <span class="input-group-text" id="basic-addon1">@ {{ user.username }}     </span>
              </div>
              <form method="get" action="{% url 'cart:cart_detail' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-dark">
                    <i class="bi-cart-fill me-1"></i>
                  Cart
                </button>
      
            </form>
           
            {% else %}
                {% if request.path == '/core/login/' %}
                <li class="nav-item"><a class="nav-link" href="{%url 'core:register'%}">Register</a></li>
                {% elif request.path == '/core/register/' %}
                <li class="nav-item"><a class="nav-link" href="{%url 'core:login'%}">Login</a></li>
                {% endif %}
            {% endif%}
            
        </div>
    </div>
</nav>

MarketGo/templates/order_detail.html
<h1>Checkout Sucessfully</h1>

MarketGo/templates/payment_completed.html
<h1>payment_completed</h1>

<h1>Invoice</h1>

MarketGo/templates/payment_failed.html
<h1>payment_failed</h1>

MarketGo/templates/register.html
{% extends 'base.html'%}
{% block content%}
{% csrf_token %}

        <!-- Header-->
    


        <div class="container">
            <div class="row">
                <div class="col-7">
        
            
            </br>  </br>
                <center>
                    <div class="col-8">
                        <br/> <br/> 
                        
 <form method="POST" action="{% url 'core:register' %}">
    {% csrf_token %}

    {{form.as_p}}

    <br/><br/>
    <button type="submit" class="btn btn-secondary"> Register </button>
  </form>
    <br/><br/>
    
                    </div>
                </center>
                </div>



                
                <div class="col-5">
                </br>  </br>
            </br>  </br>
                    <img src="/media/homepage_img.png">
                </br>  </br>
            </br>  </br>
        </br>  </br>
               
                </div>
    
     
            </div>
           </div>
 {% endblock%}

MarketGo/templates/scan_logic.html
<!-- scan.logic.html -->
{% extends 'base.html'%}
{% load static %}

{% csrf_token %}
    {% block content%}
        <!-- Include html5-qrcode.min.js -->
        <script src="{% static 'html5-qrcode.min.js' %}"></script>

        <h1>Welcome to the Home Page</h1>


        <!-- Add a button for scanning the barcode -->
    <div class="container">
        <div class="row">
<center><div id="qr-reader" class="qr-reader-custom"><button type="button" id="reader">Scan Barcode</button></div></center>
        </div>
    </div>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>

    <!-- Include jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
var html5QrcodeScanner;
function onScanSuccess(decodedText, decodedResult) {
// Make an AJAX request to your Django backend
fetch("{% url 'product:search_product' %}", {
    method: "POST",
    headers: {
        "Content-Type": "application/json",
        "X-CSRFToken": getCookie("csrftoken"),
    },
    body: JSON.stringify({ 'barcode': decodedText }),
})
.then(response => {
    if (response.ok) {
        // Parse JSON response
        return response.json();}
    else if (response.status === 404){
        return response.json();
        console.error("Error1:", response.status);
    } else {
        console.error("Error2:", response.status);
        return response.text().then(text => {
        console.error("Response Content1:", text);
        throw new Error("Failed to parse response JSON");
        });
    }
})
.then(data => {

        if (data.success) {
        // Handle the product details (assuming 'data.product' contains the details)
        console.log("Product Details:", data.product);

        // Redirect to a new page or update the UI as needed
        window.location.href = "{% url 'product:search_product' %}";
    } else {
        //handles case where the product isn't found
                window.location.href = "{% url 'product:search_product' %}"
    }
})
.catch(error => {
    console.error("Response Content2", error.response.text())
})

.finally(() => {
    // Clear the scanner, assuming it is a function provided by the library
    if (html5QrcodeScanner) {
        html5QrcodeScanner.clear();
    }
});     
}
function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== "") {
        const cookies = document.cookie.split(";");
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.startsWith(name + "=")) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;}

function onScanError(errorMessage) {
    // handle on error condition, with error message
    console.log("Error4: ", errorMessage);
}
html5QrcodeScanner = new Html5QrcodeScanner(
    "qr-reader", { fps: 10, qrbox: 250 });
    html5QrcodeScanner.render(onScanSuccess);
    window.addEventListener("beforeunload", function () {
    if (html5QrcodeScanner) {
        html5QrcodeScanner.clear();
    }
});
</script>
{% endblock%}

MarketGo/templates/view_cart.html
<!-- cart/view_cart.html -->

{% extends 'base.html' %}
{% block content %}
  <h2>Your Cart</h2>
  {% if cart_items %}
    <ul>
      {% for item in cart_items %}
        <li>{{ item.product.name }} - Quantity: {{ item.quantity }}</li>
      {% endfor %}
    </ul>
    <p>Total Price: ${{ total_price }}</p>
    <a href="{% url 'cart:remove_from_cart' item.id %}">Remove Item</a>
  {% else %}
    <p>Your cart is empty.</p>
  {% endif %}
{% endblock %}